Fix tests/motion-logger/startup-gcode-abort
Fixes:
Traceback (most recent call last):
  File "./test-ui.py", line 3, in <module>
    import linuxcnc
ImportError: /home/sw/projects/machinekit/linuxcnc/lib/python/linuxcnc.so: undefined symbol: PyString_FromString

  File "./test-ui.py", line 23
    print "UI abort"
                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("UI abort")?

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>