Fix tests/halui/jogging
Fixes the following errors:
 File "test-ui.py", line 22
    print "%.3f: %s" % (delta_t, msg)
                   ^
SyntaxError: invalid syntax

  File "test-ui.py", line 285
    print "%s starting at %.3f" % (name0, start_position0)
                              ^
SyntaxError: invalid syntax

  File "test-ui.py", line 294
    print "jogging %s positive using the private per-joint jog pins" % name0
                                                                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("jogging %s positive using the private per-joint jog pins" % name0)?

  File "test-ui.py", line 302
    print "%s did not start jogging" % name0
                                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("%s did not start jogging" % name0)?

  File "test-ui.py", line 310
    print "jogging selected joint (%s) negative" % (name1)
                                               ^
SyntaxError: invalid syntax

  File "test-ui.py", line 319
    print "%s did not start jogging" % name1
                                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("%s did not start jogging" % name1)?

  File "test-ui.py", line 349
    print "%s stopped jogging" % name0
                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("%s stopped jogging" % name0)?

  File "test-ui.py", line 366
    print "stopping jog"
                       ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("stopping jog")?

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>