Fix canterp.so installation
Fixes installation of canterp.so (introduced in
c54043254a432d214b296183545c5779d9e1b6cd).

Building rpm packages fails as follows:
    error: Installed (but unpackaged) file(s) found:
        /usr/lib64/linuxcnc

This is a result of mismatch between
  - creating directories using:
      $(DESTDIR)/lib/linuxcnc

  - installing canterp.so using:
      $(FILE) ../lib/linuxcnc/canterp.so $(DESTDIR)$(libdir)/linuxcnc

It is manifested on systems where "${libdir}" differs from "lib".

Note: this does not fixes loading canterp.so which uses hardcoded
path[1].

[1] https://github.com/LinuxCNC/linuxcnc/commit/1f733ebaf9065f5c2304c34168964f8c9605b0dc#diff-e4daea21a6d335db374a201d7386d70ef7ba440ee0d87aa462c87a051be68cffR39

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>