Fix tests/abort/feed-rate
Fixes the following errors:

  File "./test-ui.py", line 69
    print "feed rate:", s.settings[1]
                     ^
SyntaxError: Missing parentheses in call to 'print'.
Did you mean print("feed rate:", s.settings[1])?

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>