Fix tests/interp/python-self
Fixes:
 File "./interp/python-self/subs.py", line 24
    print "__init__: self not is this"
                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("__init__: self not is this")?

 File "./interp/python-self/oword.py", line 25
    print "param1 was retained, value = ", self.param1
                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("param1 was retained, value = ", self.param1)?

Sorry: TabError: inconsistent use of tabs and spaces in indentation (oword.py, line 31)

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>