Add missing <math.h> header
Fixes compilation errors:

libnml/posemath/_posemath.c: In function ‘pmMatZyxConvert’:
libnml/posemath/_posemath.c:526:9: warning: implicit declaration of function ‘fabs’ [-Wimplicit-function-declaration]
     if (fabs(zyx->y - PM_PI_2) < ZYX_Y_FUZZ) {
         ^~~~
libnml/posemath/_posemath.c:526:9: warning: incompatible implicit declaration of built-in function ‘fabs’
libnml/posemath/_posemath.c:526:9: note: include ‘<math.h>’ or provide a declaration of ‘fabs’
libnml/posemath/_posemath.c:36:1:
+#include <math.h>

libnml/posemath/_posemath.c:526:9:
     if (fabs(zyx->y - PM_PI_2) < ZYX_Y_FUZZ) {
         ^~~~
libnml/posemath/_posemath.c:529:11: warning: implicit declaration of function ‘atan2’ [-Wimplicit-function-declaration]
  zyx->x = atan2(m->y.x, m->y.y);
           ^~~~~
libnml/posemath/_posemath.c:529:11: warning: incompatible implicit declaration of built-in function ‘atan2’
libnml/posemath/_posemath.c:529:11: note: include ‘<math.h>’ or provide a declaration of ‘atan2’
libnml/posemath/_posemath.c:533:12: warning: incompatible implicit declaration of built-in function ‘atan2’
  zyx->x = -atan2(m->y.z, m->y.y);
            ^~~~~
libnml/posemath/_posemath.c:533:12: note: include ‘<math.h>’ or provide a declaration of ‘atan2’
libnml/posemath/_posemath.c: In function ‘pmMatRpyConvert’:
libnml/posemath/_posemath.c:546:9: warning: incompatible implicit declaration of built-in function ‘fabs’
     if (fabs(rpy->p - PM_PI_2) < RPY_P_FUZZ) {
         ^~~~
libnml/posemath/_posemath.c:546:9: note: include ‘<math.h>’ or provide a declaration of ‘fabs’
libnml/posemath/_posemath.c:547:11: warning: incompatible implicit declaration of built-in function ‘atan2’
  rpy->r = atan2(m->y.x, m->y.y);
           ^~~~~
libnml/posemath/_posemath.c:547:11: note: include ‘<math.h>’ or provide a declaration of ‘atan2’
libnml/posemath/_posemath.c:551:12: warning: incompatible implicit declaration of built-in function ‘atan2’
  rpy->r = -atan2(m->y.x, m->y.y);
            ^~~~~
libnml/posemath/_posemath.c:551:12: note: include ‘<math.h>’ or provide a declaration of ‘atan2’
libnml/Submakefile:19: *** unterminated variable reference.  Stop.
make: *** Waiting for unfinished jobs....
Compiling libnml/posemath/sincos.c
gcc -c  -I. -Imachinetalk/build -Imachinetalk/nanopb -Imachinetalk/include -Ilibnml/linklist -Ilibnml/cms -Ilibnml/rcs -Ilibnml/inifile -Ilibnml/os_intf -Ilibnml/nml -Ilibnml/buffer -Ilibnml/posemath -Irtapi -Irtapi_export -Ihal/lib -I../include/machinetalk/protobuf -Ihal/vtable-example -Ihal/userfunct-example -Ihal/drivers -Ihal/cython -Ihal/accessor -Iemc/nml_intf -Iemc/kinematics -Iemc/motion -Iemc/tp -Iemc/ini -Iemc/rs274ngc -Iemc/pythonplugin -I/usr/include/python2.7 -fwrapv  -fno-strict-overflow -g -Wall -funwind-tables  -DULAPI -std=gnu99 -fgnu89-inline -fPIC -DGIT_BUILD_SHA=\"'308cb1f'\"  -fPIC \
	-MP -MD -MF "objects/libnml/posemath/sincos.d" -MT "objects/libnml/posemath/sincos.o" \
	libnml/posemath/sincos.c -o objects/libnml/posemath/sincos.o
make: Leaving directory '/home/sw/projects/rpmbuild/BUILD/machinekit-308cb1f3017dc170eb460ba596a2a686a7f53b1b/src'
error: Bad exit status from /var/tmp/rpm-tmp.aZDtmT (%build)