Fix tests/limit3
Fixes:
    print "sample=%d, next_out=%.6f, vel=%.6f, seconds_to_stop=%.6f, pos_at_stop=%.6f, min=%.6f, max=%.6f" % \
                                                                                                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("sample=%d, next_out=%.6f, vel=%.6f, seconds_to_stop=%.6f, pos_at_stop=%.6f, min=%.6f, max=%.6f" % \)?

    print "max=%.3f, out=%.3f, position violation on line %s" % (max_value, out_value, line)
                                                            ^
SyntaxError: invalid syntax

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>