Fix tests/motion/g0
Fixes:
  File "motion/g0/checkresult", line 80
    print "sample 0: X starts at %.6f, not at 0.000000" % samples[0][1]
                                                      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("sample 0: X starts at %.6f, not at 0.000000" % samples[0][1])?

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>