Fix tests/tool-info/non-random
Fixes:
     print "nothing from polling error channel"
                                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("nothing from polling error channel")?

Sorry: TabError: inconsistent use of tabs and spaces in indentation (test-ui.py, line 64)

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>