Fix tests/mdi-while-queuebuster-waitflag
Fixes:
 File "mdi-while-queuebuster-waitflag/remap.py", line 13
    print "self.input_flag pre = %s" % self.input_flag
                                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("self.input_flag pre = %s" % self.input_flag)?

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>