Fix tests/build/header-sanity
Fixes the following error in case where the libtirpc is used
as an RPC implementation provider:

+ g++ -std=c++0x -DULAPI -I/home/sw/projects/machinekit/linuxcnc-rip/include -E -x c++ /home/sw/projects/machinekit/linuxcnc-rip/include/cms_xup.hh
/home/sw/projects/machinekit/linuxcnc-rip/include/cms_xup.hh:19:10: fatal error: rpc/rpc.h: No such file or directory
   19 | #include <rpc/rpc.h>  /* struct XDR */
      |          ^~~~~~~~~~~

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>